security:
    # 1. Gestion des mots de passe
    # On utilise 'plaintext' pour éviter de devoir crypter les mots de passe pour le test
    password_hashers:
        Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface: 'plaintext'

    # 2. Les Utilisateurs (STOCKÉS DANS LE CODE, PAS DANS LA BDD)
    providers:
        users_in_memory:
            memory:
                users:
                    # COMPTE ADMIN (Il a les deux rôles pour être tranquille)
                    admin@stockmaster.com: { password: '123456', roles: ['ROLE_ADMIN', 'ROLE_USER'] }

                    # COMPTE UTILISATEUR SIMPLE
                    user@stockmaster.com:  { password: '123456', roles: ['ROLE_USER'] }

    # 3. Les règles du Pare-feu (Firewall)
    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            lazy: true
            provider: users_in_memory

            # Configuration du formulaire de connexion
            form_login:
                login_path: app_login
                check_path: app_login
                enable_csrf: true
                default_target_path: app_dashboard # Redirection après succès

            # Configuration de la déconnexion
            logout:
                path: app_logout
                target: app_login

    # 4. Le Contrôle d'Accès (Qui a le droit d'aller où ?)
    access_control:
        # Tout le monde peut voir la page de login
        - { path: ^/login, roles: PUBLIC_ACCESS }

        # Il faut être au moins USER pour voir le reste du site
        # (Comme l'Admin a aussi le rôle ROLE_USER, il passera aussi)
        - { path: ^/, roles: ROLE_USER }
